
services:
  snginx:
    container_name: snginx
    build:
      context: .
      dockerfile: ./DockerFiles/Nginx
    ports:
      - 80:80
    volumes:
      - ~/Sites/ubaldodiaznunez/blog-app/api/:/var/www/vhosts/blog-app/api/
      - ~/Sites/ubaldodiaznunez/blog-app/provision/_config/nginx/docker.conf.d/:/etc/nginx/conf.d/
    networks:
      - blog-app
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./DockerFiles/PHP
    working_dir: /var/www/vhosts/blog-app/api
    ports:
      - 9000:9000
    volumes:
      - ~/Sites/ubaldodiaznunez/blog-app/api/:/var/www/vhosts/blog-app/api/
    networks:
      - blog-app

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./DockerFiles/App
    working_dir: /app/blog
    volumes:
      - ~/Sites/ubaldodiaznunez/blog-app/app/blog/:/app/blog/
    ports:
      - "3000:3000"
    networks:
      - blog-app
  
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ~/Sites/ubaldodiaznunez/blog-app/provision/_config/mysql/lib:/var/lib/mysql:cached
      - ~/Sites/ubaldodiaznunez/blog-app/provision/_config/mysql/data:/var/lib/mysql
      - ~/Sites/ubaldodiaznunez/blog-app/provision/_config/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    networks:
      - blog-app
  
networks:
  blog-app:
    driver: bridge
    